---
app:
  host: 127.0.0.1
  port: 80
  debug: False
  user: admin
  password: 123456
  cors: False
  clean_client_mm: 1
  client_expiration_time_mm: 2


log:
  log_dir: 'logs/{}'
  c_open: True
  clevel: info
  f_open: False
  flevel: info
  format: "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
  date_format: "%Y-%m-%d %A %H:%M:%S"
  file_max: 512
  file_count: 3



ntchat:
  wx_exe_path: 'C:\Program Files (x86)\Tencent\WeChat\WeChat.exe'
  wx_version: 3.6.0.18
  callback_url: 'http://82.157.161.174:30008/callback'
  qrcode_img_path: 'D:\qrcodes'


websocket:
  protocol: ws://
  host: 82.157.161.174
  prot: 30008
  path: /websocket/071cd83d12e3358e8d62ba2a36e0f296